language: java
jdk:
- oraclejdk8
notifications:
  email: false

before_script:
- "wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz"
- "tar xvfs geckodriver-v0.11.1-linux64.tar.gz"
- "pwd"
- "ls"
- "chmod 777 bin/xvfb"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script:
- ./gradlew seleniumXvfb

after_success:
- ./gradlew jacocoTestReport coveralls
- ./gradlew seleniumXvfb

deploy:
  provider: heroku
  api_key:
    secure: 54a07eb5-ee5a-40ad-b1e5-bc14ee92ee47
  app:
    master: tictactoe-staging
    production: tictactoe-production


