language: java
jdk:
- oraclejdk8
notifications:
  email: false
env:
  global:
  - ENCRYPTION_LABEL: "4a2fdc3a5352"
  - COMMIT_AUTHOR_EMAIL: "bjarnabofar@yahoo.com"

before_script:
- "wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz"
- "tar xvfs geckodriver-v0.11.1-linux64.tar.gz"
- "chmod 777 bin/xvfb"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- javadoc -d build/javadoc src/main/java/is/ru/tictactoe/Board.java src/main/java/is/ru/tictactoe/Cell.java src/main/java/is/ru/tictactoe/Point.java src/main/java/is/ru/tictactoe/Player.java src/main/java/is/ru/tictactoe/ComputerPlayer.java src/main/java/is/ru/tictactoe/HumanPlayer.java src/main/java/is/ru/tictactoe/TicTacToe.java

before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
- stack install pandoc

after_success:
- ./gradlew jacocoTestReport coveralls

deploy:
  provider: heroku
  api_key:
    secure: 54a07eb5-ee5a-40ad-b1e5-bc14ee92ee47
  app:
    master: tictactoe-staging
    production: tictactoe-production

after_deploy:
- ./gradlew seleniumXvfb
- bash ./deploy.sh



