language: java
jdk:
- oraclejdk8
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: H6gfo9g9qcaY3NHZv+YBoL2VIBnML6vk8RiQgU4caErwDR3P4n2vzrfVmKS35cduvGkasZaRCUc46WnmNnmkycYIqA4m39JsarZq64P5ANLSfsMQXYCF0VY3i8eK10+dtHIAuetUl43PXqmZl4rek5OCkBOQUfpR5Ncgt1s5R9Q2qw+DqH1qg0SZSk1OthOs7NPBZWiJijlWpS5IO4GsRFdDmfaqeUy3RHsdmT7hf9R8+P29IfKAPofe0TIHlWtFsnF3sGQVOfYIEtJ+8I3XfWie34cIc/80fYdkoA+jesR0mzpOwcpjX8Q/L2TK9P3CI0plpK490CB7+PNpH+tKrC4CAdIrRbDItRL4Txv3DvW6E9gwqG79gL8Oxu7pZUM44E86toBRFpibgMZiH6U9JMwvq/1zcViivIktQDZS2YB4dtwImzEnRpydKMdL4S+RNPD+oKXA3ZO/oAByiQaSTuigQO6+Bs60VgoBbHcOlFxZ/WFUSlcdGw9aT/nmM7v3UVu4AG7qtPgbqLAbVpbe/1SLB+B/JxrlgkmPTaiMuCAsG9VbWa9Qin858ZE825AyoGDNsjlFrK7p5STUgUn/EyeCJ++6WkwtoC5ljPis2s1lwebYBNE3+pkNYw8BVwtLcmEPLdM9FmA1KdqXrBGgUUiqWbgU93JceU/5DwngJo0=
app: serene-falls-48635
