language: java
jdk:
- oraclejdk8
notifications:
  email: false

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- ./gradlew check
- ./gradlew seleniumXvfb

after_success:
- ./gradlew jacocoTestReport coveralls
  
deploy:
  provider: heroku
  api_key:
    secure: 54a07eb5-ee5a-40ad-b1e5-bc14ee92ee47
  app:
    master: tictactoe-staging
    production: tictactoe-production
