language: java
jdk:
- oraclejdk8
notifications:
  email: false

after_success:
- ./gradlew jacocoTestReport coveralls
  
deploy:
  provider: heroku
  api_key:
    secure: 54a07eb5-ee5a-40ad-b1e5-bc14ee92ee47
  app:
    master: serene-falls-48635
    production: tictactoe-bjarnabofar
