language: java
jdk:
- oraclejdk8
notifications:
  email: false

addons:
  sauce_connect:
    username: "Bjarnabofar"
    access_key: "bd0aa525-3efa-49f2-be52-835292ef3885"


#before_script:
#- "export DISPLAY=:99.0"
#- "sh -e /etc/init.d/xvfb start"
#- sleep 3 # give xvfb some time to start

#before_install:
#- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

#script:
#- ./gradlew check
#- ./gradlew seleniumXvfb

after_success:
- ./gradlew jacocoTestReport coveralls
  
deploy:
  provider: heroku
  api_key:
    secure: 54a07eb5-ee5a-40ad-b1e5-bc14ee92ee47
  app:
    master: tictactoe-staging
    production: tictactoe-production
