/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thorhildurt15' at '10/18/16 9:06 PM' with Gradle 3.1
 *
 * @author thorhildurt15, @date 10/18/16 9:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
